- name: configuring cart
  hosts: cart
  become: yes 
  tasks:
  - name: enabling and disabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y ;
  - name: installing nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present
  - name: adding roboshop user
    ansible.builtin.user:
     name: roboshop
  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  - name: downloading application code
    ansible.builtin.get_url:
     src: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp/cart.zip
  - name: unzipping the code
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes
  - name: installing dependancies
    ansible.builtin.command: npm install
  - name: copying cart service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service
  - name: reloading daemon
    ansible.builtin.systemd_service:
     name: cart
     daemon_reload: true
  - name: starting and enabling cart
    ansible.builtin.service:
     name: cart
     state: started
     enabled: yes
