- name: configuring rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configuring yum repos of erlang
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  - name: configuring repos of rabbitmq
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
  - name: installing rabbitmq
    ansible.builtin.dnf:
     name: rabbitmq-server
     state: present
  - name: enabling and starting rabbitmq
    ansible.builtin.service:
     name: rabbitmq-server
     state: started
     enabled: yes
  - name: adding rabbitmq user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
  - name: setting permisssions for rabbitmq
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" 